### ISSUE TITLE
import users from xls .

### ISSUE THREAD

**Issue by dahantrd** [bwitting/homebridge-ttlock#10]
hi everyone . 
I'm trying to add multiple users by xls format . 
anyone has an idea or code how to add it ?
thanks .
Beny

**Comment by bwitting** [comment]
@dahantrd - I'm sure you can write a quick app using the API to import the users.  User creation/management is really beyond the scope of a homebridge plugin though.

**Comment by dahantrd** [comment]
thanks .
we mange to make it in external program i wrote .
thanks
beny



--------------------------------------------------------------------------------------------


Best Regards,

Beny Dahan
Magic Interactive LTD
www.maginet.co.il
<https://mailtrack.io/trace/link/76f29327a1f22828c86125d29a3faf0e6673fe70?url=http%3A%2F%2Fwww.maginet.co.il%2F&userId=609723&signature=24ca8b9f9fcfd065>

David Saharov 11 st. Floor 2
Rishon Letzion , ZIP: 7570713
Phone: +972-3-9415502
Fax: +972-3-9415508



‫בתאריך יום ב׳, 1 במאי 2023 ב-22:48 מאת ‪Bronson Witting‬‏ <‪
***@***.***‬‏>:‬

**Comment by dahantrd** [comment]
hi !
i want to add to my app real time picture of the user which used the lock . i added call back server and receive the data from ttlock server but it can take 10 seconds-1 minute after the lock has been opened . in the api noting mentioned about cloud call back . any suggestions ?
