### ISSUE TITLE
Gateway busy

### ISSUE THREAD

**Issue by cemilbrowne** [bwitting/homebridge-ttlock#2]
Howdy, thanks for creating this plugin - I got it setup (not without a bit of messing about with the username/password!), but am having issues with auto-lock.  

```
[8/22/2022, 3:03:23 PM] [TTLock] Basement Door unlocked successfully.
[8/22/2022, 3:07:14 PM] [TTLock] locking of Basement Door failed. The gateway is currently busy.
```

In this setup, I unlocked via homekit, the lock auto-locked itself, but still reported status = unlocked in homekit.  When I then tried to lock (via homekit), I got the message above (locking failed). 

Both the error message & status are currently incorrect.  Lock stays in "locking" mode indefinitely in HK.

**Comment by cemilbrowne** [comment]
Great troubleshooting tips - I'll do some more when I get a chance.  One note: I don't see a debug option in the TTLock settings - is there a specific item I should turn on for more debug logging?   

I'm using a Gateway v G2; gateway does show online and is associated.  Remote unlock does appear to work - and the gateway is within 2 meters (6 feet) as well.  

I'll keep debugging this one.  Getting a really solid ttlock homebridge platform would be great.

**Comment by stalkerj** [comment]
Hello.
I also got this error about gateway.
When i made username in CMD i couln't enter second part of command. Here is I got:

C:\Windows\System32>curl --ssl-no-revoke --location --request POST "https://euapi.ttlock.com/v3/user/register?clientId=xxxxxxxxxxx&clientSecret=xxxxxxxxxxxxx&username=Anton&password=xxxxxxxxx&date=CURRENTMILLIS" \
{"username":"ccecg_Anton"}curl: (6) Could not resolve host: \

C:\Windows\System32>--header "Content-Type: application/x-www-form-urlencoded" \

What did I make wrong?

**Comment by dale-tectorsolutions** [comment]
[stalkerj](https://github.com/stalkerj) It looks like it's running that command as two separate commands. Try to copy this and paste into CMD:

`curl --ssl-no-revoke --location --request POST 'https://euapi.ttlock.com/v3/user/register?clientId=[clientid]&clientSecret=[clientsecret]&username=[username]&password=[passwordasmd5]&date=CURRENTMILLIS' \
--header 'Content-Type: application/x-www-form-urlencoded' \`

**Comment by flxmrk** [comment]
When I got this "gateway busy" error - i power cycled the gateway, and everything came back online.  Hope that doesn't happen so often, but just adding my experience here.
