### ISSUE TITLE
error when trying to register a new user for the api

### ISSUE THREAD

**Issue by ssarkis** [bwitting/homebridge-ttlock#5]
this is the url i am using,  (i have changed the clientid and secret)

https://euapi.ttlock.com/v3/user/register?clientId=[10a8d9d775bb44fe9e6eef4f9cfa4444]&clientSecret=[07798da7908638e552a1e6d3de7777f4]&username=[emailaddress]&password=[21785d8e6844ea4e3d2312a9c70b666c]&date=CURRENTMILLIS

and this is the error i get

{"errcode":10001,"errmsg":"invalid client","description":"无效的client，client_id或client_secret错误"}

**Comment by ssarkis** [comment]
syntax was wrong and got ttlock developer support via wechat to help.  Managed to get the account created.

**Comment by ahmadnazirafiq** [comment]
Hi, just got a TTLock padlock. I'm stuck on this process of creating a new user. I run the below command via Terminal and its not responding with any result at all:

> curl --location --request POST 'https://euapi.ttlock.com/v3/user/register?clientId=[15ad9fccebdf4880b52185fd0bff5ace]&clientSecret=[b362451d0b6e49bf8e20aadaa31ed199]&username=[myemailaddress]&password=[2b21a5a196bcc59c3ea0d64b44c7b046]&date=CURRENTMILLIS' \
--header 'Content-Type: application/x-www-form-urlencoded' \
