### ISSUE TITLE
Dumb Question 2

### ISSUE THREAD

**Issue by smkdog420** [bwitting/homebridge-ttlock#8]
so excited for this, been trying to figure out a solution to get a padlock in HK.  Ive create the dev account and it is approved, so I am able to get the ID and Secrete.  Sorry, but dumber question......I'm on,.....Create a New User on Developer Account.  Where do I create this new user account?  On the developer website?  I cant seem to figure out where.  I used a one email when I first set up the lock with the app then a different email account when I did the dev part.  Sorry feel like a dumb ass but totally stocked on getting this in.

**Comment by smkdog420** [comment]
well, that didn't get me far.  Anyone have any tips/tricks/help for my dumb ass?  Bought lock and bridge with hopes of getting this in hk

**Comment by bwitting** [comment]
Hey @smkdog420.  Any luck here?  You need to create the new user account via the API.  Easiest way is with curl, the command is in the readme: https://github.com/bwitting/homebridge-ttlock#readme.  It looks like there is also a way to transfer a consumer account via API - I will look into that and get some documentation.

**Comment by smkdog420** [comment]
No I had given up, but will give it renewed effort.  Not techie, but I can usually follow directions, I’ll check out the readme tonight.  Thanks

**Comment by bwitting** [comment]
No worries, ping me if and let me know if you get it working
